"""empty message

Revision ID: 2174e1c74a1d
Revises: a3b62d01c5a0
Create Date: 2020-05-02 19:35:25.452343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2174e1c74a1d'
down_revision = 'a3b62d01c5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
