"""empty message

Revision ID: 27300d772e40
Revises: 49c22e785e6b
Create Date: 2020-05-03 01:10:39.364601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27300d772e40'
down_revision = '49c22e785e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'likes_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('lists', 'posts_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('lists', 'share_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('lists', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('lists', 'visit_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'visit_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('lists', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('lists', 'share_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('lists', 'posts_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('lists', 'likes_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
