"""empty message

Revision ID: 4a540d964198
Revises: 27300d772e40
Create Date: 2020-05-03 01:29:18.001331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a540d964198'
down_revision = '27300d772e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'likes_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'list_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'share_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'visit_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'visit_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'share_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'list_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'likes_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
