"""empty message

Revision ID: 8642509b17b5
Revises: 4a540d964198
Create Date: 2020-05-04 18:34:33.892565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8642509b17b5'
down_revision = '4a540d964198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'private')
    op.drop_column('posts', 'private')
    op.drop_column('lists', 'private')
    # ### end Alembic commands ###
